# Generated by Django 5.2 on 2025-07-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='img')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, choices=[('Chothes and wear', 'CLOTHES AND WARE'), ('Home interiors', 'HOME INTERIORS'), ('Computer and tech', 'COMPUTER AND TECH'), ('Tools and equipment', 'TOOLS AND EQUIPMENT'), ('Sport and outdoor', 'SPORT AND OUTDOOR'), ('Animal and pets', 'ANIMAL AND PETS'), ('Machinery tools', 'MACHINERY TOOLS'), ('Others', 'OTHERS')], null=True)),
            ],
        ),
    ]
