# Generated by Django 5.2 on 2025-07-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_image_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Clothes and wear', 'CLOTHES AND WEAR'), ('Home interiors', 'HOME INTERIORS'), ('Computer and tech', 'COMPUTER AND TECH'), ('Tools and equipment', 'TOOLS AND EQUIPMENT'), ('Sport and outdoor', 'SPORT AND OUTDOOR'), ('Animal and pets', 'ANIMAL AND PETS'), ('Machinery tools', 'MACHINERY TOOLS'), ('Others', 'OTHERS')], max_length=50, null=True),
        ),
    ]
