# Generated by Django 5.2 on 2025-07-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.CharField(blank=True, choices=[('mainImage', 'Main Image'), ('image2', 'Image 2'), ('image3', 'Image 3'), ('image4', 'Image 4'), ('image5', 'Image 5')], max_length=10, null=True),
        ),
    ]
