# Generated by Django 5.2 on 2025-07-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.CharField(blank=True, choices=[('image1', 'Image 1'), ('image2', 'Image 2'), ('image3', 'Image 3'), ('image4', 'Image 4'), ('image5', 'Image 5')], max_length=10, null=True),
        ),
    ]
