# Generated by Django 5.2 on 2025-07-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_image1_alter_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Chothes and wear', 'CLOTHES AND WARE'), ('Home interiors', 'HOME INTERIORS'), ('Computer and tech', 'COMPUTER AND TECH'), ('Tools and equipment', 'TOOLS AND EQUIPMENT'), ('Sport and outdoor', 'SPORT AND OUTDOOR'), ('Animal and pets', 'ANIMAL AND PETS'), ('Machinery tools', 'MACHINERY TOOLS'), ('Others', 'OTHERS')], max_length=50, null=True),
        ),
    ]
