# Generated by Django 5.2 on 2025-07-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageHomeOutdoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='HomePage_HomeOutdoor', to='store.product')),
            ],
        ),
    ]
