# Generated by Django 5.2 on 2025-07-16 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_homepagehomeoutdoor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeElectronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='HomePage_HomeElectroics', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='HomeRecomended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='HomePage_HomeRecomended', to='store.product')),
            ],
        ),
    ]
