# Generated by Django 5.2 on 2025-07-24 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_homeelectronics_homerecomended'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealsOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealProducts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DealsAndOffers', to='store.product')),
            ],
        ),
    ]
