# Generated by Django 5.2 on 2025-07-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_dealsoffers'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealsoffers',
            name='dealtime',
            field=models.DateField(blank=True, help_text='Start or common deal date', null=True),
        ),
        migrations.AddField(
            model_name='dealsoffers',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount in percentage', max_digits=5, null=True),
        ),
    ]
