# Generated by Django 5.2 on 2025-07-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_dealsoffers_dealtime_dealsoffers_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealsoffers',
            name='deal_ends_at',
            field=models.DateTimeField(blank=True, help_text='Exact end datetime for the deal', null=True),
        ),
        migrations.AlterField(
            model_name='dealsoffers',
            name='dealtime',
            field=models.DateField(blank=True, help_text='Start date of the deal', null=True),
        ),
    ]
