# Generated by Django 5.2 on 2025-07-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_dealsoffers_deal_ends_at_alter_dealsoffers_dealtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealsoffers',
            old_name='dealtime',
            new_name='deal_start_time',
        ),
    ]
