# Generated by Django 5.2 on 2025-07-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_dealtime_dealsoffers_deal_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsoffers',
            name='deal_start_time',
            field=models.DateTimeField(blank=True, help_text='Start date of the deal', null=True),
        ),
    ]
