# Generated by Django 5.2 on 2025-07-27 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_dealsoffers_deal_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_start_time', models.DateTimeField(help_text='Start time of the deal')),
                ('deal_ends_at', models.DateTimeField(help_text='End time of the deal')),
            ],
        ),
        migrations.CreateModel(
            name='DealProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, help_text='Discount for this product', max_digits=5)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_products', to='store.dealtime')),
            ],
        ),
        migrations.DeleteModel(
            name='DealsOffers',
        ),
    ]
