# Generated by Django 5.2 on 2025-07-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_dealtime_dealproduct_delete_dealsoffers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.CharField(blank=True, choices=[('image1', 'Image 1'), ('image2', 'Image 2'), ('image3', 'Image 3'), ('image4', 'Image 4'), ('image5', 'Image 5')], max_length=2000, null=True),
        ),
    ]
