# Generated by Django 5.2 on 2025-07-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_type_product_producttype_product_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
