# Generated by Django 5.2 on 2025-08-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_product_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
